# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
ActiveRecord::Base.transaction do
  Country.create(domain: "AD", name:cn "安道尔", name_en: "Andorra")
  Country.create(domain: "AE", name:cn "阿联酋", name_en: "United Arab Em.");
  Country.create(domain: "AF", name:cn "阿富汗", name_en: "Afghanistan");
  Country.create(domain: "AG", name:cn "安提瓜和巴布达", name_en: "Antigua and Barbuda");
  Country.create(domain: "AI", name:cn "安圭拉", name_en: "Anguilla");
  Country.create(domain: "AL", name:cn "阿尔巴尼亚", name_en: "Albania");
  Country.create(domain: "AM", name:cn "亚美尼亚", name_en: "Armenia");
  Country.create(domain: "AN", name:cn "荷属安的列斯群岛", name_en: "NETHERLANDS ANTILLES");
  Country.create(domain: "AO", name:cn "安哥拉", name_en: "Angola");
  Country.create(domain: "AR", name:cn "阿根廷", name_en: "Argentina");
  Country.create(domain: "AS", name:cn "美属萨摩亚", name_en: "American Samoa");
  Country.create(domain: "AT", name:cn "奥地利", name_en: "Austria");
  Country.create(domain: "AU", name:cn "澳大利亚", name_en: "Australia");
  Country.create(domain: "AW", name:cn "阿鲁巴群岛", name_en: "Aruba");
  Country.create(domain: "AZ", name:cn "阿塞拜疆", name_en: "Azerbaijan");
  Country.create(domain: "BA", name:cn "波斯尼亚", name_en: "Bosnia");
  Country.create(domain: "BB", name:cn "巴巴多斯", name_en: "Barbados");
  Country.create(domain: "BD", name:cn "孟加拉", name_en: "Bangladesh");
  Country.create(domain: "BE", name:cn "比利时", name_en: "Belgium");
  Country.create(domain: "BF", name:cn "布基纳法索", name_en: "Burkina Faso");
  Country.create(domain: "BG", name:cn "保加利亚", name_en: "Bulgaria");
  Country.create(domain: "BH", name:cn "巴林", name_en: "Bahrain");
  Country.create(domain: "BI", name:cn "布隆迪", name_en: "Burundi");
  Country.create(domain: "BJ", name:cn "贝宁", name_en: "Benin");
  Country.create(domain: "BL", name:cn "圣巴瑟米（法）", name_en: "Saint Barthelemy");
  Country.create(domain: "BM", name:cn "百慕大", name_en: "Bermuda");
  Country.create(domain: "BN", name:cn "文莱", name_en: "Brunei");
  Country.create(domain: "BO", name:cn "玻利维亚", name_en: "Bolivia");
  Country.create(domain: "BQ", name:cn "荷兰加勒比区", name_en: "Bonaire Sint Eustatius Saba");
  Country.create(domain: "BR", name:cn "巴西", name_en: "Brazil");
  Country.create(domain: "BS", name:cn "巴哈马", name_en: "Bahamas");
  Country.create(domain: "BT", name:cn "不丹", name_en: "Bhutan");
  Country.create(domain: "BV", name:cn "布韦岛（挪）", name_en: "Bouvet Island");
  Country.create(domain: "BW", name:cn "博茨瓦纳", name_en: "Botswana");
  Country.create(domain: "BY", name:cn "白俄罗斯", name_en: "Belarus");
  Country.create(domain: "BZ", name:cn "伯利兹", name_en: "Belize");
  Country.create(domain: "CA", name:cn "加拿大", name_en: "Canada");
  Country.create(domain: "CC", name:cn "科科斯群岛", name_en: "Cocos (Keeling) Islands");
  Country.create(domain: "CD", name:cn "刚果民主共和国", name_en: "The Democratic Republic of the Congo");
  Country.create(domain: "CF", name:cn "中非共和国", name_en: "Central African Republic");
  Country.create(domain: "CG", name:cn "刚果", name_en: "Congo");
  Country.create(domain: "CH", name:cn "瑞士", name_en: "Switzerland");
  Country.create(domain: "CI", name:cn "科特迪瓦", name_en: "Côte d'Ivoire");
  Country.create(domain: "CK", name:cn "库克群岛", name_en: "Cook Islands");
  Country.create(domain: "CL", name:cn "智利", name_en: "Chile");
  Country.create(domain: "CM", name:cn "喀麦隆", name_en: "Cameroon");
  Country.create(domain: "CN", name:cn "中国", name_en: "China");
  Country.create(domain: "CO", name:cn "哥伦比亚", name_en: "Colombia");
  Country.create(domain: "CR", name:cn "哥斯达黎加", name_en: "Costa Rica");
  Country.create(domain: "CU", name:cn "古巴", name_en: "Cuba");
  Country.create(domain: "CV", name:cn "佛得角", name_en: "Cape Verde");
  Country.create(domain: "CW", name:cn "库拉索", name_en: "Curacao");
  Country.create(domain: "CX", name:cn "圣诞岛", name_en: "Christmas Island");
  Country.create(domain: "CY", name:cn "塞浦路斯", name_en: "Cyprus");
  Country.create(domain: "CZ", name:cn "捷克", name_en: "Czech");
  Country.create(domain: "DE", name:cn "德国", name_en: "Germany");
  Country.create(domain: "DJ", name:cn "吉布提", name_en: "Djibouti");
  Country.create(domain: "DK", name:cn "丹麦", name_en: "Denmark");
  Country.create(domain: "DM", name:cn "多米尼克", name_en: "Dominica");
  Country.create(domain: "DO", name:cn "多米尼加", name_en: "Dominican Rep");
  Country.create(domain: "DZ", name:cn "阿尔及利亚", name_en: "Algeria");
  Country.create(domain: "EC", name:cn "厄瓜多尔", name_en: "Ecuador");
  Country.create(domain: "EE", name:cn "爱沙尼亚", name_en: "Estonia");
  Country.create(domain: "EG", name:cn "埃及", name_en: "Egypt");
  Country.create(domain: "EH", name:cn "西撒哈拉", name_en: "Western Sahara");
  Country.create(domain: "ER", name:cn "厄立特里亚", name_en: "Eritrea");
  Country.create(domain: "ES", name:cn "西班牙", name_en: "Spain");
  Country.create(domain: "ET", name:cn "埃塞俄比亚", name_en: "Ethiopia");
  Country.create(domain: "EU", name:cn "欧盟", name_en: "EU");
  Country.create(domain: "FI", name:cn "芬兰", name_en: "Finland");
  Country.create(domain: "FJ", name:cn "斐济", name_en: "Fiji");
  Country.create(domain: "FK", name:cn "福克兰群岛（马尔维纳斯群岛）", name_en: "Falkland Islands (Malvinas)");
  Country.create(domain: "FM", name:cn "密克罗尼西亚联邦", name_en: "Micronesia, Federated States of");
  Country.create(domain: "FO", name:cn "法罗群岛", name_en: "Faroe Islands");
  Country.create(domain: "FR", name:cn "法国", name_en: "France");
  Country.create(domain: "GA", name:cn "加蓬", name_en: "Gabon");
  Country.create(domain: "GB", name:cn "英国", name_en: "Great Britain");
  Country.create(domain: "GD", name:cn "格林纳达", name_en: "Grenada");
  Country.create(domain: "GE", name:cn "格鲁吉亚", name_en: "Georgia");
  Country.create(domain: "GF", name:cn "法属圭亚那", name_en: "French Guiana");
  Country.create(domain: "GG", name:cn "格恩西岛", name_en: "Guernsey");
  Country.create(domain: "GH", name:cn "加纳", name_en: "Ghana");
  Country.create(domain: "GI", name:cn "直布罗陀", name_en: "Gibraltar");
  Country.create(domain: "GL", name:cn "格陵兰", name_en: "Greenland");
  Country.create(domain: "GM", name:cn "冈比亚", name_en: "Gambia");
  Country.create(domain: "GN", name:cn "几内亚", name_en: "Guinea");
  Country.create(domain: "GP", name:cn "瓜德罗普", name_en: "Guadeloupe");
  Country.create(domain: "GQ", name:cn "赤道几内亚", name_en: "Equatorial Guinea");
  Country.create(domain: "GR", name:cn "希腊", name_en: "Greece");
  Country.create(domain: "GS", name:cn "南乔治亚岛", name_en: "South Georgia and the Islands");
  Country.create(domain: "GT", name:cn "危地马拉", name_en: "Guatemala");
  Country.create(domain: "GU", name:cn "关岛", name_en: "Guam");
  Country.create(domain: "GW", name:cn "几内亚比绍", name_en: "Guinea-Bissau");
  Country.create(domain: "GY", name:cn "圭亚那", name_en: "Guyana");
  Country.create(domain: "HK", name:cn "中国香港", name_en: "Hong Kong");
  Country.create(domain: "HM", name:cn "赫德岛和麦克唐纳群岛", name_en: "Heard Island and McDonald Islands");
  Country.create(domain: "HN", name:cn "洪都拉斯", name_en: "Honduras");
  Country.create(domain: "HR", name:cn "克罗地亚", name_en: "Croatia");
  Country.create(domain: "HT", name:cn "海地", name_en: "Haiti");
  Country.create(domain: "HU", name:cn "匈牙利", name_en: "Hungary");
  Country.create(domain: "ID", name:cn "印度尼西亚", name_en: "Indonesia");
  Country.create(domain: "IE", name:cn "爱尔兰", name_en: "Ireland");
  Country.create(domain: "IL", name:cn "以色列", name_en: "Israel");
  Country.create(domain: "IN", name:cn "印度", name_en: "India");
  Country.create(domain: "IO", name:cn "英属印度洋领地", name_en: "British Indian Ocean Territory");
  Country.create(domain: "IQ", name:cn "伊拉克", name_en: "Iraq");
  Country.create(domain: "IR", name:cn "伊朗", name_en: "Iran");
  Country.create(domain: "IS", name:cn "冰岛", name_en: "Iceland");
  Country.create(domain: "IT", name:cn "意大利", name_en: "Italy");
  Country.create(domain: "JM", name:cn "牙买加", name_en: "Jamaica");
  Country.create(domain: "JO", name:cn "约旦", name_en: "Jordan");
  Country.create(domain: "JP", name:cn "日本", name_en: "Japan");
  Country.create(domain: "KE", name:cn "肯尼亚", name_en: "Kenya");
  Country.create(domain: "KG", name:cn "吉尔吉斯斯坦", name_en: "Kyrgyzstan");
  Country.create(domain: "KH", name:cn "柬埔寨", name_en: "Cambodia");
  Country.create(domain: "KI", name:cn "基里巴斯", name_en: "Kiribati");
  Country.create(domain: "KM", name:cn "科摩罗", name_en: "Comoros");
  Country.create(domain: "KN", name:cn "圣基茨和尼维斯", name_en: "Saint Kitts and Nevis");
  Country.create(domain: "KP", name:cn "朝鲜", name_en: "Democratic People's Republic of Korea");
  Country.create(domain: "KR", name:cn "韩国", name_en: "South Korea");
  Country.create(domain: "KV", name:cn "科索沃", name_en: "");
  Country.create(domain: "KW", name:cn "科威特", name_en: "Kuwait");
  Country.create(domain: "KY", name:cn "开曼群岛", name_en: "Cayman Islands");
  Country.create(domain: "KZ", name:cn "哈萨克斯坦", name_en: "Kazakhstan");
  Country.create(domain: "LA", name:cn "老挝", name_en: "Laos");
  Country.create(domain: "LB", name:cn "黎巴嫩", name_en: "Lebanon");
  Country.create(domain: "LC", name:cn "圣卢西亚", name_en: "Saint Lucia");
  Country.create(domain: "LI", name:cn "列支敦士登", name_en: "Liechtenstein");
  Country.create(domain: "LK", name:cn "斯里兰卡", name_en: "Sri Lanka");
  Country.create(domain: "LR", name:cn "利比里亚", name_en: "Liberia");
  Country.create(domain: "LS", name:cn "莱索托", name_en: "Lesotho");
  Country.create(domain: "LT", name:cn "立陶宛", name_en: "Lithuania");
  Country.create(domain: "LU", name:cn "卢森堡", name_en: "Luxembourg");
  Country.create(domain: "LV", name:cn "拉脱维亚", name_en: "Latvia");
  Country.create(domain: "LY", name:cn "利比亚", name_en: "Libya");
  Country.create(domain: "MA", name:cn "摩洛哥", name_en: "Moroco");
  Country.create(domain: "MC", name:cn "摩纳哥", name_en: "Monaco");
  Country.create(domain: "MD", name:cn "摩尔多瓦", name_en: "Republic of Moldova");
  Country.create(domain: "ME", name:cn "黑山", name_en: "Montenegro");
  Country.create(domain: "MG", name:cn "马达加斯加", name_en: "Madagascar");
  Country.create(domain: "MH", name:cn "马绍尔群岛", name_en: "Marshall Islands");
  Country.create(domain: "MK", name:cn "马其顿", name_en: "Republic of Macedonia");
  Country.create(domain: "ML", name:cn "马里", name_en: "Mali");
  Country.create(domain: "MM", name:cn "缅甸", name_en: "Myanmar");
  Country.create(domain: "MN", name:cn "蒙古", name_en: "Mongolia");
  Country.create(domain: "MO", name:cn "中国澳门", name_en: "Macau");
  Country.create(domain: "MP", name:cn "北马里亚纳群岛", name_en: "Northern Mariana Islands");
  Country.create(domain: "MQ", name:cn "马提尼克", name_en: "Martinique");
  Country.create(domain: "MR", name:cn "毛里塔尼亚", name_en: "Mauritania");
  Country.create(domain: "MS", name:cn "蒙特塞拉特", name_en: "Montserrat");
  Country.create(domain: "MT", name:cn "马耳他", name_en: "Malta");
  Country.create(domain: "MU", name:cn "毛里求斯", name_en: "Mauritius");
  Country.create(domain: "MV", name:cn "马尔代夫", name_en: "Maldives");
  Country.create(domain: "MW", name:cn "马拉维", name_en: "Malawi");
  Country.create(domain: "MX", name:cn "墨西哥", name_en: "Mexico");
  Country.create(domain: "MY", name:cn "马来西亚", name_en: "Malaysia");
  Country.create(domain: "MZ", name:cn "莫桑比克", name_en: "Mozambique");
  Country.create(domain: "NA", name:cn "纳米比亚", name_en: "Namibia");
  Country.create(domain: "NC", name:cn "新喀里多尼亚", name_en: "New Caledonia");
  Country.create(domain: "NE", name:cn "尼日尔", name_en: "Niger");
  Country.create(domain: "NF", name:cn "诺福克岛", name_en: "Norfolk Island");
  Country.create(domain: "NG", name:cn "尼日利亚", name_en: "Nigeria");
  Country.create(domain: "NI", name:cn "尼加拉瓜", name_en: "Nicaragua");
  Country.create(domain: "NL", name:cn "荷兰", name_en: "Netherlands");
  Country.create(domain: "NO", name:cn "挪威", name_en: "Norway");
  Country.create(domain: "NP", name:cn "尼泊尔", name_en: "Nepal");
  Country.create(domain: "NR", name:cn "瑙鲁", name_en: "Nauru");
  Country.create(domain: "NU", name:cn "纽埃", name_en: "Niue");
  Country.create(domain: "NZ", name:cn "新西兰", name_en: "New Zealand");
  Country.create(domain: "OM", name:cn "阿曼", name_en: "Oman");
  Country.create(domain: "PA", name:cn "巴拿马", name_en: "Panama");
  Country.create(domain: "PE", name:cn "秘鲁", name_en: "Peru");
  Country.create(domain: "PF", name:cn "法属波利尼西亚", name_en: "French Polynesia");
  Country.create(domain: "PG", name:cn "巴布亚新几内亚", name_en: "Papua New Guinea");
  Country.create(domain: "PH", name:cn "菲律宾", name_en: "Philippines");
  Country.create(domain: "PK", name:cn "巴基斯坦", name_en: "Pakistan");
  Country.create(domain: "PL", name:cn "波兰", name_en: "Poland");
  Country.create(domain: "PM", name:cn "圣皮埃尔和密克隆", name_en: "Saint Pierre and Miquelon");
  Country.create(domain: "PN", name:cn "皮特凯恩", name_en: "Pitcairn");
  Country.create(domain: "PR", name:cn "波多黎各", name_en: "Puerto Rico");
  Country.create(domain: "PS", name:cn "加沙地带", name_en: "Gaza Strip");
  Country.create(domain: "PT", name:cn "葡萄牙", name_en: "Portugal");
  Country.create(domain: "PW", name:cn "帕劳", name_en: "Palau");
  Country.create(domain: "PY", name:cn "巴拉圭", name_en: "Paraguay");
  Country.create(domain: "QA", name:cn "卡塔尔", name_en: "Qatar");
  Country.create(domain: "RE", name:cn "留尼旺群岛", name_en: "Reunion");
  Country.create(domain: "RO", name:cn "罗马尼亚", name_en: "Romania");
  Country.create(domain: "RS", name:cn "塞尔维亚", name_en: "Serbia");
  Country.create(domain: "RU", name:cn "俄罗斯", name_en: "Russia");
  Country.create(domain: "RW", name:cn "卢旺达", name_en: "Rwanda");
  Country.create(domain: "SA", name:cn "沙特阿拉伯", name_en: "Saudi Arabia");
  Country.create(domain: "SB", name:cn "所罗门群岛", name_en: "Solomon Islands");
  Country.create(domain: "SC", name:cn "塞舌尔", name_en: "Seychelles");
  Country.create(domain: "SD", name:cn "苏丹", name_en: "Sudan");
  Country.create(domain: "SE", name:cn "瑞典", name_en: "Sweden");
  Country.create(domain: "SG", name:cn "新加坡", name_en: "Singapore");
  Country.create(domain: "SH", name:cn "圣赫勒拿，阿森松岛和特里斯坦达库尼亚", name_en: "Saint Helena, Ascension and Tristan Da Cunha");
  Country.create(domain: "SI", name:cn "斯洛文尼亚", name_en: "Slovenia");
  Country.create(domain: "SJ", name:cn "斯瓦尔巴特群岛", name_en: "Svalbard");
  Country.create(domain: "SK", name:cn "斯洛伐克", name_en: "Slovakia");
  Country.create(domain: "SL", name:cn "塞拉利昂", name_en: "Sierra Leone");
  Country.create(domain: "SM", name:cn "圣马力诺", name_en: "San Marino");
  Country.create(domain: "SN", name:cn "塞内加尔", name_en: "Senegal");
  Country.create(domain: "SO", name:cn "索马里", name_en: "Somalia");
  Country.create(domain: "SR", name:cn "苏里南", name_en: "Suriname");
  Country.create(domain: "SS", name:cn "南苏丹", name_en: "South Sudan");
  Country.create(domain: "ST", name:cn "圣多美和普林西比", name_en: "Sao Tome and Principe");
  Country.create(domain: "SV", name:cn "萨尔瓦多", name_en: "El Salvador");
  Country.create(domain: "SX", name:cn "荷属圣马丁", name_en: "Sint Maarten");
  Country.create(domain: "SY", name:cn "叙利亚", name_en: "Syrian Arab Republic");
  Country.create(domain: "SZ", name:cn "斯威士兰", name_en: "Swaziland");
  Country.create(domain: "TC", name:cn "特克斯和凯科斯群岛", name_en: "Turks and Caicos Islands");
  Country.create(domain: "TD", name:cn "乍得", name_en: "Chad");
  Country.create(domain: "TG", name:cn "多哥", name_en: "Togo");
  Country.create(domain: "TH", name:cn "泰国", name_en: "Thailand");
  Country.create(domain: "TJ", name:cn "塔吉克斯坦", name_en: "Tajikistan");
  Country.create(domain: "TK", name:cn "托克劳群岛", name_en: "Tokelau");
  Country.create(domain: "TL", name:cn "东帝汶", name_en: "East Timor");
  Country.create(domain: "TM", name:cn "土库曼斯坦", name_en: "Turkmenistan");
  Country.create(domain: "TN", name:cn "突尼斯", name_en: "Tunisia");
  Country.create(domain: "TO", name:cn "汤加", name_en: "Tonga");
  Country.create(domain: "TR", name:cn "土耳其", name_en: "Turkey");
  Country.create(domain: "TT", name:cn "特里尼达和多巴哥", name_en: "Trinidad and Tobago");
  Country.create(domain: "TV", name:cn "图瓦卢", name_en: "Tuvalu");
  Country.create(domain: "TW", name:cn "中国台湾", name_en: "Taiwan");
  Country.create(domain: "TZ", name:cn "坦桑尼亚", name_en: "Tanzania, United Republic of");
  Country.create(domain: "UA", name:cn "乌克兰", name_en: "Ukraine");
  Country.create(domain: "UG", name:cn "乌干达", name_en: "Uganda");
  Country.create(domain: "UM", name:cn "美国本土外小岛屿", name_en: "United States Minor Outlying Islands");
  Country.create(domain: "US", name:cn "美国", name_en: "USA");
  Country.create(domain: "UY", name:cn "乌拉圭", name_en: "Uruguay");
  Country.create(domain: "UZ", name:cn "乌兹别克斯坦", name_en: "Uzbekistan");
  Country.create(domain: "VA", name:cn "梵蒂冈", name_en: "Vatican City State");
  Country.create(domain: "VC", name:cn "圣文森特和格林纳丁斯", name_en: "Saint Vincent and the Grenadines");
  Country.create(domain: "VE", name:cn "委内瑞拉", name_en: "Venezuela");
  Country.create(domain: "VG", name:cn "英属维尔京群岛", name_en: "British Virgin lslands");
  Country.create(domain: "VI", name:cn "维京群岛", name_en: "Virgin Islands");
  Country.create(domain: "VN", name:cn "越南", name_en: "Vietnam");
  Country.create(domain: "VU", name:cn "瓦努阿图", name_en: "Vanuatu");
  Country.create(domain: "WF", name:cn "瓦利斯群岛和富图纳群岛", name_en: "Wallis and Futuna");
  Country.create(domain: "WS", name:cn "萨摩亚", name_en: "Samoa");
  Country.create(domain: "YE", name:cn "也门", name_en: "Yemen");
  Country.create(domain: "YT", name:cn "马约特岛", name_en: "Mayotte");
  Country.create(domain: "ZA", name:cn "南非", name_en: "South Africa");
  Country.create(domain: "ZM", name:cn "赞比亚", name_en: "Zambia");
  Country.create(domain: "ZW", name:cn "津巴布韦", name_en: "Zimbabwe");
end
